### PR TITLE
Further settings page enhancements #94

### PR DESCRIPTION
**Pull request by bb-Ricardo**
* move config definitions and functions to `config.h`
* fix responsive design of index and settings pages
* config endpoint moved from '/all' to '/config.json'
* simplified config setting parsing in app.js

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
First of all, thank you for this incredible fast merging.

Do you test the changes before merging? Just wondering.

**Comment by WarDrake** [comment]
I think he does after I broke it with one of my commits before :P

**Comment by NimmLor** [comment]
He, just downloads and quickly checks if it compiles, if it does he merges it. He might really test it when he publishes a new release :)

:joy:

**Comment by NimmLor** [comment]
I'm currently working 65h+ a week and therefore very busy at the moment. I'm hoping that I'll have more time to work on it in the future.

**Comment by bb-Ricardo** [comment]
> I'm currently working 65h+ a week and therefore very busy at the moment. I'm hoping that I'll have more time to work on it in the future.

ohh wow, then it's even more incredible that you're taking the time and keep merging PRs.

Hope this amount of working hours are not lasting too long as they can wear you down a lot.

I will try to do some more refinement work on here.

**Comment by NimmLor** [comment]
Awesome! I'm currently doing my civil service (=Zivildienst) with 40h/week whilst working for two startups as a freelance full stack react-native app developer 😅

I was thinking of adding you two guys as collaborators to the repo 🤔

**Pull request merged**
