### PR TITLE
Adding mDNS ability to the webserver to avoid looking for the ip

### LINKED ISSUE #28: Improvement : mDNS
mDNS would be a great improvement over looking for the IP on devices that support it.

### PR DESCRIPTION
**Pull request by WarDrake**
fixes NimmLor/esp8266-nanoleaf-webserver#28
adding mDNS for devices that support it, it's based off the configured HOSTNAME const.

### CODE REVIEW

**Comment by NimmLor** [comment]
Hi, thanks for your contributions. I've merged the changes, but there will be a big update/rewrite probably next week that includes your improvements with all necessary preprocessor statements.

**Comment by WarDrake** [comment]
That's great news, I've been making some changes to the library over the last couple days for my personal use and figured some of them might be nice to share with everyone here.

Looking forward to your rewrite, and great job on this. thanks.

**Comment by NimmLor** [comment]
A friend of mine is also working on an android/(ios) app for managing multiple leds at once. He is building it using the ionic framework.

The update will include the following features:
- sync all leds with the windows audio device using an optional WPF application
  - networkscanner to automatically detect all device in the network
  - control the essential functions of the web ui using the desktop app
  - many new patterns to react to the sound
  - run in background (systemtray)
  - darkmode

image

- updating the leds via OTA
- using the leds as an ambilight behind a tv with an usb cable (integration of Adalight)

**Comment by WarDrake** [comment]
Oh, that is beautiful!
I tested the sound module, made a couple changes there too and it works fine, but the volume is horrible on the only mic module I have so I ended up not using it, being able to capture the windows audio device is a great solution to that tho, I'm looking forward to it.

as for the extra patterns, will we be able to save custom ones without updating the firmware? that'd be an amazing improvement to someone like me that really doesn't graphically coordinate, I could get someone else to design nice ones when they play with it and save them so I can use them later.

**Pull request merged**
